CREATE USER Noelia IDENTIFIED BY 'soytonta468';
 GRANT ALL PRIVILEGES ON *.* TO 'Noelia'@'188.166.174.201' IDENTIFIED BY 'soytonta468' WITH GRANT OPTION;
 
 
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, material, url, url1, url2) values('Abanico','Abanico con flores','Un bonito abanico con rosas azules y rojas. Perfecto para los días de calor o para una llevarlo a una boda.','3.5','madera','/static/imgProductos/11/1.png','/static/imgProductos/11/1.1.jpg','/static/imgProductos/11/1.2.jpg');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, material, url) values('Azulejo personalizado 1','Azulejo para cualquier sitio','Este azulejo lo podras poner en cualquier sitio. En la cocina para para poder recordar Úbeda cuando este cocinando o comiendo o incluso en el dormitorio','3.5','Cerámica','static/imgProductos/12/1.png');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, url, url1) values('Bolso','Bolso de flores estampadas','Bolso mediano para llevar todo cuando salgas de fiesta','10','static/imgProductos/3/1.png','static/imgProductos/3/1.2.png');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, material, url,url1,url2) values('Cenicero de Úbeda','Cenicero con frases','Un cecinero de cerámica perfecto para los fumadores o para regalar','4','Cerámica','static/imgProductos/4/1.png','static/imgProductos/4/1.2.png','static/imgProductos/4/1.3.png');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, url) values('Cesta Lucía','Cesta personalizada','Cesta perfecta para ir de picnic.','9.90','static/imgProductos/5/1.png');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, material, url,url1) values('Mortero','Mortero para cocinar','Mortero perfecto para cocinar','16','Madera de olivo','static/imgProductos/6/1.png','static/imgProductos/6/1.2.png');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, material, url,url1) values('Vasos de chupito','Vaso de chupito para probar todas las bebidas','Este vaso de chupito es perfecto para juntarse con los amigos y pasar un buen rato','2.50','Cristal','static/imgProductos/7/1.png','static/imgProductos/7/1.1.png');
insert into PRODUCTOS (nombreProducto, descripcionCorta, descripcionLarga, precio, material, url,url1) values('Taza abuela','Taza personalizada para las abuelas','Regalo perfecto para las abuelas.','5','static/imgProductos/8/1.png','static/imgProductos/8/1.1.png');